[workspace]
members = ["sys"]

[package]
name = "n2n-rs"
version = "3.1.1"
edition = "2021"
license = "GPL-3.0"

[dependencies]
thiserror = "1.0.61"
anyhow = "1.0.86"
libc = "0.2.155"

[dependencies.n2n-sys]
path = "sys"